"#version 400\n"
"in highp vec3 aPosition;\n"
"\n"
"uniform highp mat4 uModelMatrix;\n"
"uniform highp mat4 uViewProjMatrix;\n"
"\n"
"void main(void)\n"
"{\n"
"	vec3 positionWS = (uModelMatrix * vec4(aPosition.x, aPosition.y, aPosition.z, 1.0)).xyz;\n"
"	gl_Position = uViewProjMatrix * vec4(positionWS, 1.0);\n"
"	gl_Position.z -= gl_Position.w * 0.00001f;\n"
"}\n"
