"#version 400\n"
"in highp vec3 aPosition;\n"
"in highp vec2 aTexcoord;\n"
"\n"
"uniform highp mat4 uModelMatrix;\n"
"uniform highp mat4 uViewProjMatrix;\n"
"\n"
"out highp vec3 vPositionWS;\n"
"out highp vec2 vTextureCoord;\n"
"\n"
"void main(void)\n"
"{\n"
"	vPositionWS = (uModelMatrix * vec4(aPosition.x, aPosition.y, aPosition.z, 1.0)).xyz;\n"
"	vTextureCoord = aTexcoord;\n"
"	gl_Position = uViewProjMatrix * vec4(vPositionWS, 1.0);\n"
"}\n"
