"#version 400\n"
"precision highp float;\n"
"\n"
"uniform lowp vec4 uBoxColor;\n"
"in highp vec3 vPositionWS;\n"
"in highp vec2 vTextureCoord;\n"
"\n"
"uniform sampler2D colorTex;\n"
"\n"
"layout(location = 0) out vec4 finalColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec3 lightDir = vec3(0.1f, 0.6f, -0.4f);\n"
"    vec3 normalWS = normalize(cross(dFdx(vPositionWS), dFdy(vPositionWS)));\n"
"    float diffuse = max(dot(-lightDir, normalWS), 0.0f);\n"
"\n"
"    vec3 srcColor = uBoxColor.w > 0.5f ? texture(colorTex, vTextureCoord).xyz : uBoxColor.xyz;\n"
"    finalColor = vec4(srcColor * (diffuse * 0.2f + 0.8f), 1.0f);\n"
"}\n"
