"#version 400\n"
"in highp vec3 aPosition;\n"
"\n"
"uniform mediump mat4 uModelMatrix;\n"
"uniform mediump mat4 uViewProjMatrix;\n"
"\n"
"out highp vec3 vPositionWS;\n"
"\n"
"void main(void)\n"
"{\n"
"	vPositionWS = (uModelMatrix * vec4(aPosition.x, aPosition.y, aPosition.z, 1.0)).xyz;\n"
"	gl_Position = uViewProjMatrix * vec4(vPositionWS, 1.0);\n"
"}\n"
