"#version 400\n"
"precision highp float;\n"
"\n"
"uniform lowp vec4 uBoxColor;\n"
"\n"
"layout(location = 0) out vec4 finalColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    finalColor = uBoxColor;\n"
"}\n"
