"#version 400\n"
"precision highp float;\n"
"\n"
"uniform lowp vec4 uBoxColor;\n"
"in highp vec3 vPositionWS;\n"
"\n"
"layout(location = 0) out vec4 diffuseColor;\n"
"\n"
"void main(void)\n"
"{\n"
"	vec3 lightDir = vec3(0.1f, 0.6f, -0.4f);\n"
"	vec3 normalWS = normalize(cross(dFdx(vPositionWS), dFdy(vPositionWS)));\n"
"	float diffuse = max(dot(-lightDir, normalWS), 0.0f);\n"
"\n"
"    diffuseColor = uBoxColor * (diffuse * 0.8f + 0.2f);\n"
"}\n"