"#version 400\n"
"precision highp float;\n"
"\n"
"in highp vec2 vTextureCoord;\n"
"\n"
"uniform sampler2D colorTex;\n"
"\n"
"layout(location = 0) out vec4 finalColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec3 srcColor = texture(colorTex, vTextureCoord).xyz;\n"
"    float alpha = min(dot(srcColor, vec3(2.0, 2.0, 2.0)), 1.0);\n"
"    finalColor = vec4(srcColor, alpha);\n"
"}\n"
