"#version 400\n"
"in highp vec2 aPosition;\n"
"\n"
"uniform highp vec4 uScreenPosition;\n"
"\n"
"out highp vec2 vTextureCoord;\n"
"\n"
"void main(void)\n"
"{\n"
"   vTextureCoord = aPosition.xy;\n"
"   gl_Position = vec4(uScreenPosition.xy + (aPosition.xy * 2.0 - 1.0) * uScreenPosition.zw, 0.0, 1.0);\n"
"}\n"
